[package]
name = "minuterie"
version = "0.1.0"
authors = ["Girkov Arpa <girkovarpa@protonmail.com>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1
#panic = "abort"

[dependencies]
winsafe = "0.0.4"